# Generated by Django 5.1.2 on 2024-11-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='capa',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
